package de.unifrankfurt.texttechnologie.data;

import java.io.IOException;
import java.util.Map;

import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;

/**
 * Parses the given data to be processed.
 * @author Timo Homburg
 *
 */
public interface ParserAPI {
	
	/**Exports the result generated by the program.
	 * @throws IOException */
	public void exportResult(double[] exportVector) throws IOException;
	/**Parses the data out of the given file.
	 * @throws MatrixException if the matrix is not a squared one*/
	public double[][] parseData() throws MatrixException;
	/**Parses a graph given in a TEI file and extracts the adjacency matrix.
	 * @return the adjacency matrix
	 * @throws SAXException on parsing errors
	 * @throws ParserConfigurationException on parsing configuration errors
	 * @throws IOException on IO errors*/
	public double[][] parseGraphML() throws ParserConfigurationException, SAXException, IOException;
	/**Returns the given wordmap.*/
	public Map<Integer,String> getWordmap();
}
